---
- name: test my new module
  hosts: localhost
  vars:
    tripleo_get_flatten_params: "{{ lookup('file', 'molecule/mock_params') | from_yaml }}"
    tripleo_role_list: "{{ lookup('file', 'molecule/mock_roles') | from_yaml }}"
    tripleo_all_nodes: "{{ lookup('file', 'molecule/mock_ironic_all') | from_yaml }}"
    hci_profile_config: "{{ lookup('file', 'molecule/mock_hci_profile_config') | from_yaml }}"
    hci_profile: default
    num_phy_cores_per_numa_node_for_pmd: 1
    hw_data_required: true
  tasks:
  - name: run the new module
    tripleo_derive_hci_parameters:
      #tripleo_heat_resource_tree: "{{ tripleo_heat_resource_tree }}"
      #introspection_data: "{{ hw_data }}"
      average_guest_cpu_utilization_percentage: 50
      average_guest_memory_size_in_mb: 2048
    register: hci_derived_parameters
  - name: dump test output
    debug:
      msg: '{{ hci_derived_parameters }}'

  - name: add hci_derived_parameters to derived_parameters_result
    set_fact:
      mock_derived_parameters_result:
        NovaReservedHostMemory: "{{ hci_derived_parameters['nova_reserved_mem_mb'] }}"
        NovaCPUAllocationRatio: "{{ hci_derived_parameters['cpu_allocation_ratio'] }}"
    when:
      - hci_derived_parameters['valid_input']

  - name: Fail if tripleo_derive_hci_parameters module failed
    fail:
      msg: "tripleo_derive_hci_parameters failed: {{ hci_derived_parameters['message'] }}"
    when:
      - not hci_derived_parameters['valid_input']
